# 1 Python Basics
Jupyter Notebook reference: [https://www.javadrive.jp/python/jupyter-notebook/](https://www.javadrive.jp/python/jupyter-notebook/)  
Installation and startup sections not needed (we'll launch via Anaconda).

## 1.1 Hello World

In [112]:
print("Hello World")

Hello World


### Practice

Combine output using + operator

In [113]:
print("Hello" + " " + "world" + " ^_^" + "6")

Hello world ^_^6


In [114]:
x = 20
print(x)

20


In [115]:
x = 10
print(x)

10


## 1.2 Arithmetic Operations

In [116]:
x = 10
y = 20
z = x - y
s = x + y
w = x * y
m = x / y
print(x, y, z, s, w, m)

10 20 -10 30 200 0.5


### Exponentiation

In [117]:
print(2**2, 2**3, 2**5, 2**(1/3), 2**0.5, 2**(1/2))

4 8 32 1.2599210498948732 1.4142135623730951 1.4142135623730951


In [118]:
2**(0.5)

1.4142135623730951

## 1.3 Data Types

### Integer (int) type

In [119]:
x = 10
print(x)
type(x)

10


int

### Floating point (float) type

In [120]:
y = 10.2
print(y)
type(y)

10.2


float

### String (str) type

In [121]:
name = "Liu Qingfeng"
print(name)
type(name)

Liu Qingfeng


str

### Boolean (bool) type: True and False

In [122]:
s0 = (8 > 5)
print(s0)
type(s0)

True


bool

In [123]:
s1 = (5 > 3)
print(s1)
type(s1)
print(s0*s1)

True
1


### List type

In [124]:
l1 = [3, 5, 9]
print(l1)
type(l1)

[3, 5, 9]


list

In [125]:
l2 = ['A', 5, "python", "0.01","Class is over 你好"]
print(l2)
type(l2)

['A', 5, 'python', '0.01', 'Class is over 你好']


list

In [126]:
print(l2[0])
type(l2[0])

A


str

In [127]:
type(l2[1])

int

In [128]:
type(l2[2])

str

In [129]:
print(l2[-3])
type(l2[-3])

python


str

## 1.4 Introduction to Numpy Module

In [130]:
import numpy as np  # Abbreviated as np

In [131]:
x = np.array([2, 4, 9])  # Array method
print(x)
type(x)

[2 4 9]


numpy.ndarray

## Matrix Operations
#### Reference: [https://note.nkmk.me/python-numpy-matrix/](https://note.nkmk.me/python-numpy-matrix/)

In [132]:
x = np.array([[1, 2],[3,4]])
print(f"x = \n{x}")

x = 
[[1 2]
 [3 4]]


In [133]:
y = np.array([[10,100],[100,1]])
print(f"y = \n{y}")
print("x * y = ")
print(x * y)  # Element-wise multiplication
print(x@y)    # Matrix multiplication
print(np.dot(x,y))

y = 
[[ 10 100]
 [100   1]]
x * y = 
[[ 10 200]
 [300   4]]
[[210 102]
 [430 304]]
[[210 102]
 [430 304]]


In [134]:
x = np.array([[1, 2],[10, 20],[300, 400]])
print(x)
x.shape  # Outputs the shape: 3 rows × 2 columns

[[  1   2]
 [ 10  20]
 [300 400]]


(3, 2)

In [135]:
y = np.array([[3, 4, 5, 6],[7, 8, 9, 5]])
print(y, y.shape)

[[3 4 5 6]
 [7 8 9 5]] (2, 4)


In [136]:
# x*y  # Cannot multiply due to size mismatch

In [137]:
x@y  # Matrix multiplication

array([[  17,   20,   23,   16],
       [ 170,  200,  230,  160],
       [3700, 4400, 5100, 3800]])

#### Inverse Matrix

In [138]:
x = np.array([[1, 2],[3,4]])
xinv = np.linalg.inv(x)
print(np.dot(x,xinv))  # Product of x and xinv
print(x@xinv)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


#### Determinant

In [139]:
np.linalg.det(x)

-2.0000000000000004

#### Eigenvalues and Eigenvectors

In [140]:
w, v = np.linalg.eig(x)
print('Eigenvalues:', w)
print('Eigenvectors:', v)

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors: [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


## 1.5 For Loops
Display natural numbers from 1 to 10

In [141]:
for i in np.arange(10):
    x = (i + 1)
    print(x)

1
2
3
4
5
6
7
8
9
10


### Sum numbers from 1 to 10

In [142]:
xsum = 0
for i in np.arange(10):
    xsum += (i + 1)
    print(xsum)

1
3
6
10
15
21
28
36
45
55


# Practice Problems
1. Calculate the product sum of natural numbers from 1 to 10 using a for loop.
2. Calculate the product sum of [2, 5, 1, 8] using a for loop.

## 1.6 If Conditions

In [143]:
# Regular if statement example
x = 8
if x > 10:
    print("x is greater than 10")
elif x > 7:
    print("x is greater than 7")
else:
    print("x is 7 or less")

x is greater than 7


## 1.7 Functions

### Sum calculation function

In [144]:
def mysum(x):
    xsum = 0
    for i in np.arange(len(x)):
        print(i)
        xsum += x[i]
    return xsum

In [145]:
x = [1,2,3,58,6,4,6,67,7,8,7]
print(x)
mysum(x)

[1, 2, 3, 58, 6, 4, 6, 67, 7, 8, 7]
0
1
2
3
4
5
6
7
8
9
10


169

In [146]:
y = [20,30,40,50,60,0.1]
z = mysum(y)
print(z)

0
1
2
3
4
5
200.1


### Practice Problem: 
The heights of 5 people are 150,160,165,180,190 cm, and their weights are 60,50,70,50,100 kg respectively. 
Find the standard weight formula online (height(m)^2 × 22), and if the 5 people are within ±3 kg of standard weight, 
judge as standard; otherwise obese or thin.

In [147]:
x = np.array([[150,160,165,180,190],
              [60,50,70,50,80]])
StW = (x[0][:]/100)**2*22
print("Standard Weights:", StW)

Standard Weights: [49.5   56.32  59.895 71.28  79.42 ]


In [148]:
print('Height:', x[0][1])
print('Weights:', x[1][:])

Height: 160
Weights: [60 50 70 50 80]


In [149]:
for i in np.arange(5):
    if x[1][i] > StW[i]+3:
        print(f'Person {i+1}: Obese')
    elif x[1][i] < StW[i]-3:
        print(f'Person {i+1}: Thin')
    else:
        print(f'Person {i+1}: Standard')

Person 1: Obese
Person 2: Thin
Person 3: Obese
Person 4: Thin
Person 5: Standard


# Pandas Introduction
## Preparation: Upload DATA01.xls to the same folder (using upload button in left panel)

In [150]:
import pandas as pd
# !pip install openpyxl
# !pip install xlrd

In [151]:
df01 = pd.read_csv('../DATA01.csv')
df02 = pd.read_csv('../CAPM02.csv', skiprows=1)
print("DATA01 head:")
print(df01.head())
print("\nCAPM02 head:")
print(df02.head())
X = df01[["Weight"]]
print("\nWeight column:")
print(X)

DATA01 head:
       No  Weight  Height
0  161111     172      59
1  161112     166      58
2  161113     164      65
3  161114     175      73
4  161115     149      41

CAPM02 head:
   Unnamed: 0     NTT  NIKKEI     NTT.1  NIKKEI.1  Unnamed: 5
0        12.0     NaN     NaN  479000.0    9174.0         NaN
1         1.0 -0.0872 -0.0516  439000.0    8713.0         NaN
2         2.0 -0.0930 -0.0247  400000.0    8500.0         NaN
3         3.0  0.0793 -0.0012  433000.0    8490.0         NaN
4         4.0 -0.0546 -0.0612  410000.0    7986.0         NaN

Weight column:
    Weight
0      172
1      166
2      164
3      175
4      149
5      144
6      161
7      159
8      172
9      167
10     166
11     187
12     179
13     177
14     198
15     152
16     169
17     159
18     164
19     163
20     178
21     143
22     173
23     145
24     153
25     164
26     177
27     164
28     166
29     175
30     166
31     153
32     165
33     152
34     156
35     189
36     147
37     163


In [152]:
df01.tail(1)  # Show last row

No  Weight  Height
49  161160     180      75

In [153]:
df01.loc[0:3,'Weight']

0    172
1    166
2    164
3    175
Name: Weight, dtype: int64

In [154]:
df01.loc[0,:]

No        161111
Weight       172
Height        59
Name: 0, dtype: int64

In [155]:
df01.loc[0:2,:]

No  Weight  Height
0  161111     172      59
1  161112     166      58
2  161113     164      65